tcpui :
  restart: always
  build : tomcatpui
  links :
    - "dbpui:docker_primes_db"
  ports :
    - "7777:8080"
  environment:
    - PRIMESUI_CACHE=true
    - PRIMESUI_TESTING=false
    - PRIMESUI_SESSION=true
    - PRIMESUI_DEBUG=false
  volumes:
    - ./primesui.war:/usr/local/tomcat/webapps/primesui.war
    - /var/log/primesui/logs:/usr/local/tomcat/logs

dbpui :
  restart: always
  build : mysqlpui
  ports :
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=bumblebeeadmin
    - MYSQL_USER=optimus
    - MYSQL_PASSWORD=bumblebee
    - MYSQL_DATABASE=primes
  volumes:
    - /var/db/primesui-dbpui:/var/lib/mysql/
