tcpui :
  restart: always
  build : tomcatpui
  links : 
    - "dbpui:docker_primes_db"
  ports :
    - "7777:8080"
  environment:
    - ENV PRIMESUI_CACHE   true
    - ENV PRIMESUI_TESTING false
    - ENV PRIMESUI_SESSION true
    - ENV PRIMESUI_DEBUG   false
  volumes:
    - ./primesui.war:/usr/local/tomcat/webapps/primesui.war
    - /var/log/primesui/logs:/usr/local/tomcat/logs

dbpui :
  restart: always
  build : mysqlpui
  environment:
    - MYSQL_ROOT_PASSWORD=bumblebeeadmin
    - MYSQL_USER=optimus
    - MYSQL_PASSWORD=bumblebee
    - MYSQL_DATABASE=primes
  volumes:
    - /var/db/primesui-dbpui:/var/lib/mysql/

